tasks 15-30
PatzD/python_lasoft_PatrykD_homework pull request #4
Opened 2022-08-08 22:23 UTC by PatzD

tasks 15-30 
not sure about what sample input for task 27 is supposed to be, left comment in code in regards to that

2022-08-10 08:20 UTC, OlenaOhranchukLasoft requested changes
Please, rewrite the tasks according the comments

2022-08-10 08:20 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_17(og_array):
The tasks is correct. But, please, do it in another way - using just loops without using built-in `list` methods.

2022-08-10 08:20 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_18(og_array):
The tasks is correct. But, please, do it in another way - using just loops without using built-in `list` methods.

2022-08-10 08:20 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_19(og_array):
This function changes incoming data - og_array. Which is not the responsibility of this function. In such case it is unexpected and dangerous. Please, rewrite it in two ways: 1) using only loops without using built-in `list` methods, 2) using built-in `list` methods

2022-08-10 08:20 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_20(og_array):
Implementation is correct, but a little bit complicated. Rewrite it using `break`.

2022-08-10 08:20 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_21(og_array):
Rewrite it using only loops

2022-08-10 08:20 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +    #im not sure about the input here, is it simply going to be a 2 dimensional array, an array of arrays?
Yes, it's going to be 2 dimensional array, like [[2,3], [3,5]]. And should become {2:3, 3:5}

2022-08-10 23:58 UTC, PatzD commented on statements_syntax/main.py
> +def task_20(og_array):
i think i misunderstood the task initially, its supposed to stop adding any numbers that come after 17?

2022-08-10 23:59 UTC, PatzD commented on statements_syntax/main.py
> +def task_21(og_array):
im not sure i understood what you meant here correctly, did you mean to  not use the step option when traversing the loop?

2022-08-11 05:35 UTC, OlenaOhranchukLasoft requested changes
A couple of additional comments

2022-08-11 05:35 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_17(og_array):
Approved

2022-08-11 05:35 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +    maxim, minim = 0, 0
This initialization will not work with negative numbers.
Correct way is 
```
if not og_array:
    return None
maxim, minim = og_array[0], og_array[0]
```

2022-08-11 05:35 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_18(og_array):
Approved

2022-08-11 05:35 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +    return total / (len(og_array) - 2)
The average value will be incorrect in case array has more than 2 elements which are equal `maxim` or `minim` elements.

2022-08-11 05:35 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_20(og_array):
Yes, stop after 17

2022-08-11 05:35 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_21(og_array):
Yes, without step option

2022-08-12 14:58 UTC, OlenaOhranchukLasoft approved these changes
Some comments

2022-08-12 14:58 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +def task_20(og_array):
Approved

2022-08-12 14:58 UTC, OlenaOhranchukLasoft commented on statements_syntax/main.py
> +    return total / (len(og_array) - 2)
Please, take this warning into account for other tasks.

2022-08-12 19:00 UTC, merged